apiVersion: v1
kind: Service
metadata:
  name: nirn-discovery
  namespace: nirn-system
  labels:
    app: nirn-proxy
spec:
  clusterIP: None
  selector:
    app: nirn-proxy
  ports:
    - name: metrics
      port: 9000
      targetPort: 9000
    - name: gossip
      port: 7946
    - name: http
      port: 8080
